ananalytics methods was updated
janis-commerce/app-analytics pull request #10
Opened 2024-02-07 13:52 UTC by GonzaFran

LINK DE TICKET: *

https://janiscommerce.atlassian.net/browse/APPSRN-267

DESCRIPCIÓN DEL REQUERIMIENTO: *

CONTEXTO:

Actualmente, estamos utilizando analytics en las 3 aplicaciones de janis. 

Analytics, a grandes rasgos, se encarga de recolectar información y enviarla a la consola de google firebase como “eventos”. Los eventos son acciones provocadas voluntariamente (o no) por el usuario, y cada uno de estos contiene información que, luego de ser recibida, es organizada y utilizada para elaborar informes sobre la aplicación.
PROBLEMA:

Revisando el dashboard de analytics, nos encontramos con que los informes presentan una gran cantidad de datos que están siendo recibidos como “not set” y, en base al análisis por parte del equipo, se determinó que esto se debe a que los parametros custom que definimos se aplican para todos los eventos. ¿Qué significa esto? que si se produce un evento (el que sea)  que NO INCLUYA uno de estos parametros custom, entonces este será establecido como “not set”.

Esto aplica para los eventos que establecimos en el package y también para los [eventos automáticos/nativos](https://support.google.com/analytics/answer/9234069?hl=es).
NECESIDAD:

Necesitamos empezar a reducir la aparición de estos datos “not set” en los informes, por lo que todos los eventos que tenemos implementados actualmente deberán enviar una cantidad de data básica que será el CORE de nuestros informes de analytics.

La información CORE será la siguiente:
```js

{
  appVersion, //se recibe cuando se crea una nueva instancia de clase.
  userEmail, //este, y los siguientes, se obtienen mediante el metodo getUserInfo()
  userId,
  client,
  language
}

```

Esta información deberá ser obligatoria para todos nuestros eventos y, en caso de no estar presente, debe impedir el envío de eventos a firebase.

DESCRIPCIÓN DE LA SOLUCIÓN: *

Se agregó una validación que comprueba que los datos del usuario, obtenidos mediante el metodo initialize, contengan toda la información marcada como requerida.

En caso de que esta validación no se cumpla se frena el envío de eventos a analytics.

Se creo el archivo requiredInitialData que es un array que contiene los nombres de las keys consideradas como requeridas: Este array luego es importado dentro de cada util de validación de datos para reducir el código repetido en todas las funciones de eventos.

Se modificaron los datos requeridos de cada evento para que, además de los requeridos por default, cada uno tengas sus propios parametros requeridos.

Se amplió la utilidad de customEvent agregando un parametro extra a la función. Este nuevo parametro debe ser un array de strings que represente cuáles serán los datos requeridos para ese evento custom especifico.

Se agregaron los datos CORE a los datos que envía el método sendScreenTracking

CÓMO SE PUEDE PROBAR? *

Para probarlo se debe vincular el package al repositorio en el que quiera probarlo.

También se deben eliminar las validaciones de entorno de desarrollo para que los metodos de la clase analytics puedan enviar eventos a firebase.

Como se cambió el funcionamiento del metodo sendScreenTracking posiblemente tenga que cambiar la manera en la que se está usando en el archivo App.js de su aplicación.

Para poder probar el metodo actualizado deberá reemplazar la importación de analytics de la siguiente manera:

Actualmente importamos de esta manera:
```js
import Analytics from '@janiscommerce/app-analytics
```

esto debe reemplazarse por:

```js
import analytics from 'src/utils/analytics' //en este caso estamos importando la instancia generada de analytics en el repositorio
```

En caso de no tener una instancia generada, deberá hacerlo:

```js
const analytics = new Analytics({appVersion: VERSION_NAME});
```

El resto de funciones deberían ejecutarse de la misma manera ya que no hubo cambios significativos en ellas.

2024-02-16 20:12 UTC, dam788 requested changes
Actualizate la info de README.md

2024-02-16 21:14 UTC, dam788 approved these changes

2024-02-19 19:19 UTC, christian97dd commented on lib/utils/index.js
> +  const hasAllProperties = !updatedProperties
tucu, en este caso para ganar mayor legibilidad y evitarte una iteración más, te conviene reemplazar esta línea por:
`return updatedProperties.every((value) => dataKeys.includes(value))`

2024-02-19 19:20 UTC, christian97dd requested changes
se deja un comentario

2024-02-19 19:44 UTC, GonzaFran commented on lib/utils/index.js
> +  const hasAllProperties = !updatedProperties
Piola cris, gracias, ahi lo fixee. Es verdad, es mucho más simple y claro jaja

2024-02-19 20:06 UTC, christian97dd approved these changes

2024-02-19 20:07 UTC, merged