Added debug mode to Analytics class
janis-commerce/app-analytics pull request #13
Opened 2024-11-28 19:12 UTC by pablonortiz

LINK DE TICKET: *
https://janiscommerce.atlassian.net/browse/APPSRN-346

LINK DE SUBTAREA:
https://janiscommerce.atlassian.net/browse/APPSRN-347

DESCRIPCIÓN DEL REQUERIMIENTO: *

Tras realizar desarrollos en el package de Analytics se llegó a la conclusión de que se requiere contar con un modo debug para facilitarle las pruebas al dev debido a que hoy en día es un proceso tedioso el modificar el package para poder probarlo en ambiente de dev

DESCRIPCIÓN DE LA SOLUCIÓN: *

Se agregó una nueva key al constructor de la clase Analytics, el cuál se llama isDebugMode, si no se pasa esta key al instanciar una clase de Analytics será por defecto false, en caso de ser false se ejecutará la función isDevEnv cómo ya se venía haciendo hoy en día, en caso de ser true se ignorará la función isDevEnv y se ejecutará la acción que envía la información a Analytics

CÓMO SE PUEDE PROBAR? *

Para probarlo hay que vincular el package con yalc y tirar un npm install

Dentro del archivo dónde se instancie la clase de Analytics en el repo que se esté probando, pasarle una key más dentro del objeto el cuál sera isDebugMode en true, de la siguiente manera:

`const analytics = new Analytics({appVersion: VERSION_NAME, isDebugMode: true});`

Luego, probar dentro de la app que se haya vinculado el enviar una acción de Analytics y verificar que se envie correctamente

2024-11-29 13:22 UTC, GonzaFran requested changes
@pablonortiz revisate los condicionales de la clase en analytics

2024-11-29 13:22 UTC, GonzaFran commented on lib/analytics.js
> +      if (this.isDebugMode || (!this.isDebugMode && !isDevEnv())) {
@pablonortiz esta condición, y todas las repetidas, se pueden simplificar a:

```js
  if (this.isDebugMode || !isDevEnv()) {
  //...
  }
```

Así la condición para que se envíe el evento se cumpliría cuando:
- Nosotros, localmente, activemos el modo debug pasandole el argumento isDebug en `true`
- La app se ejecute en entornos que no son de desarrollo, o sea, la condición actual.

2024-11-29 13:39 UTC, pablonortiz commented on lib/analytics.js
> +      if (this.isDebugMode || (!this.isDebugMode && !isDevEnv())) {
Ahí lo corregí @GonzaFran !

2024-11-29 15:08 UTC, GonzaFran approved these changes

2024-12-04 18:11 UTC, christian97dd requested changes
se dejan comentarios

2024-12-04 18:11 UTC, christian97dd commented on lib/analytics.js
> +      if (this.isDebugMode || !isDevEnv()) {
aca te faltó volar el isDevEnv(), la idea es que desde la app se le mande dentro de params asi:
`params: {isDebugMode: isDevEnv()}`
de esa manera tenemos control desde dentro de la app y no tenemos que modificarlo desde node modules

2024-12-04 18:11 UTC, christian97dd commented on lib/analytics.js
> +    if (this.isDebugMode || !isDevEnv()) {
lo mismo en este caso y el resto

2024-12-04 19:03 UTC, pablonortiz commented on lib/analytics.js
> +    if (this.isDebugMode || !isDevEnv()) {
Listo! Ahí borré todas las implementaciones de isDevEnv en todo el package y también lo eliminé directamente, porque no se va a estar usando, y lo reemplacé con el isDebugMode

2024-12-05 14:37 UTC, christian97dd approved these changes

2024-12-05 14:40 UTC, merged