events was updated with required params validations
janis-commerce/app-analytics pull request #7
Opened 2023-11-02 16:29 UTC by GonzaFran

LINK DE TICKET: *

https://janiscommerce.atlassian.net/browse/APPSRN-237

DESCRIPCIÓN DEL REQUERIMIENTO: *

Se necesita actualizar las funciones actionEvent y customEvent para que toda la información enviada que no sea considerada como requerida sea enviada en el campo dataEvent. Esto es necesario para poder hacer un seguimineto en base a un parametro especifico.

También necesitamos agregar parametros requeridos en el metodo customEvent para que esa información sea detallada.

Los parametros son: userEmail, userId, client, appVersion

DESCRIPCIÓN DE LA SOLUCIÓN: *

Se modificaron los metodos customEvent y actionEvent para que toda la información, por fuera de la declarada como requerida, sea incluida dentro del objeto dataEvent, que es enviado como parametro de ambos eventos.

Se armó la util validateRequiredStringParams que se encarga de validar los parametros requeridos con los recibidos, y en caso de que estos parametros no superen la validación se retorna un error haciendo referencia a que los parametros son requeridos. Esta función luego es implementada en los metodos customEvent y actionEvent para validar los parametros.

CÓMO SE PUEDE PROBAR? *

Cómo es una refactorización de lo que ya existía previamente se puede hacer las pruebas modificando los test de los metodos mencionados y la nueva utils.
En caso de querer hacer la prueba directamente en el repo deberá vincularlo a través de yalc y posteriormente ejecutar los metodos con los parametros requeridos y opcionales que quiera enviar. 
Tenga en cuenta que estos 2 metodos no se encuentran implementados en ningun repo, por lo que su detección por parte de analytics puede llegar a demorar.

2023-11-03 13:36 UTC, colomfernando requested changes

2023-11-03 13:36 UTC, colomfernando commented on lib/actionEvent.js
> +    await validateRequiredStringParams(params, requiredData);
esta funcion no hace falta que sea asyncronica

2023-11-03 13:36 UTC, colomfernando commented on lib/actionEvent.js
> +    requiredData.forEach((attribute) => {
Aca estaria mejor usar un reduce para no mutar el argumento params. Podrias hacer el reduce que comento validando que si la key que necesitas sacar que sea data del evento no este en las keys requeridas, lo guardas en el objeto nuevo. De esta manera params queda tal cual se envio como argumento

2023-11-07 17:57 UTC, WilliamSaya-lvl30 requested changes

2023-11-07 17:57 UTC, WilliamSaya-lvl30 commented on lib/customEvent.js
> +    const [requiredParams, remainingParams] = Object.keys(params).reduce(
Este reduce se utiliza en actionEvent tambien y es practicamente igual, se podria astraer y sacar una utils, asi se evita código repetido

2023-11-07 17:57 UTC, WilliamSaya-lvl30 commented on lib/utils/index.js
> +    return params;
Esta funcion por la manera en que se utiliza solo se encarga de tirar errores, es confuso que retorne params si nunca se utiliza ese valor, dejaria solamente el return true del final.
el requiredParams.forEach lo meteria dentro de un if y ya esta.

2023-11-08 15:29 UTC, WilliamSaya-lvl30 approved these changes

2023-11-08 18:50 UTC, pablonortiz approved these changes

2023-11-13 14:16 UTC, pablodamianberdun requested changes
agregar jsdoc a las utils

2023-11-13 14:16 UTC, pablodamianberdun commented on lib/utils/index.js
> +export const splitRequiredAndRemainingParams = (
@GonzaFran podrias agregarle jsdoc a estas funciones para a futuro saber que formato de params espera y en que formato esta lo que retorna

2023-11-13 16:11 UTC, pablodamianberdun approved these changes

2023-11-13 16:15 UTC, merged