analytics class was added
janis-commerce/app-analytics pull request #8
Opened 2023-11-15 14:42 UTC by GonzaFran

LINK DE TICKET: *

https://janiscommerce.atlassian.net/browse/JWMSAPP-1222

DESCRIPCIÓN DEL REQUERIMIENTO: *

Contamos con el pkg de [analytics](https://github.com/janis-commerce/app-analytics) para enviar eventos y el objetivo es poder implementarlo en distintos partes del flujo de las apps. Hoy estamos usando un solo evento que es userInfoEvent y el de las pantallas. El problema que tenemos es que si seguimos con la misma implementacion, vamos a estar obligados a usar en cada evento varias funcionalidades para obtener datos del usuario cuando podemos hacerlo una vez

Necesidad

Se necesita crear modulo con distintos metodos, que al ejecutar cada uno de ellos, ya obtenga la informacion del usuario

DESCRIPCIÓN DE LA SOLUCIÓN: *

Se creo la clase analytics en el pkg, la cual contiene los metodos para enviar acciones, enviar información de usuario y enviar eventos modificados.
Al momento de instanciarla, la clase debe recibir un objeto que contenga toda la información necesaria para poder trabajar inicialmente con los metodos.
Se eliminó la exportación de los metodos actionEvent, customEvent y userInfoEvent, ya que estos ahora van a ser contenidos en la clase analytics.

Se agregó el parametro screenName en el metodo actionEvent, para que sea un parametro obligatorio, esto para asegurarnos en qué pantalla se realiza la acción y poder trackear esa información.

CÓMO SE PUEDE PROBAR? *

Para probarlo se debe importar la clase Analyitcs

`import {Analyitcs} from '@janiscommerce/app-analytics`

Posteriormente se debe instanciarla teniendo en cuenta que es necesario esta información minima:

`const eventData = {
  language: 'en-US',
  appName: 'janis-app',
  device: 'SM-102',
  osVersion: 'android 12',
  userEmail: 'janis@janis.im',
  userId: 'a1b2c3d4e5f6g7',
  client: 'janis',
  appVersion: '1.22.0',
}`

Dependiendo de qué acción se quiera enviar esta información puede ser suficiente o puede ser necesario agregar algún parametro extra (como es el caso de ActionEvent, que necesitará una key "screenName").

Instanciandola y luego invocandola con el metodo asociado al evento que se quiera enviar:

`const analytics = new Analytics(eventData)

analytics.sendAction('testingAction',{screeName:'Home'})
`

2023-11-16 16:54 UTC, WilliamSaya-lvl30 requested changes

2023-11-16 16:54 UTC, WilliamSaya-lvl30 commented on lib/index.js
> +export {Analytics, screenViewEvent};
En mi opinión se debería exportar solamente la clase Analitics y mantener todos los metodos centralizados en la misma, por mas que el metodo screenViewEvent no requiera tantos parametros como los otros.

2023-11-16 18:33 UTC, WilliamSaya-lvl30 approved these changes

2023-11-16 21:11 UTC, dam788 requested changes
@GonzaFran Te deje algunos comentarios, parecen muchos pero en realidad son cosas repetidas. Cualquier cosa avisame

2023-11-16 21:11 UTC, dam788 commented on lib/index.js
> +export {Analytics};
cambialo a `export {default} from './analitics';`

2023-11-16 21:11 UTC, dam788 commented on lib/analitics.js
> +    this.eventData =
La propiedad **eventData** declaralo afuera del constructor y despues dentro lo inicializas. Ej:

```
eventData;

  constructor(params) {
    this.eventData = params;
  }
```
Quizas si necesitas si o si validar el params hacete una util que te haga la validación:

```
eventData;

  constructor(data) {
    this.eventData = validateParams(data);
  }
```
Otra cosa que podes hacer es iniciar con un valor predeterminado las keys del objeto del constructor, y de paso volas la validación. Probalo, no se si anda pero me parece una buena alternativa:

```
eventData;

  constructor({ language = '', appName = '', device = '', osVersion = '', ...params } = {}) {
    this.eventData = params;
  }
```

2023-11-16 21:11 UTC, dam788 commented on lib/analitics.js
> +      !Object.keys(params).length || typeof params !== 'object' ? {} : params;
Mismo **validateParams(params);**

2023-11-16 21:11 UTC, dam788 commented on lib/analitics.js
> +      typeof params === 'object' && !!Object.keys(params).length ? params : {};
Mismo **validateParams(data);**

2023-11-16 21:11 UTC, dam788 commented on lib/analitics.js
> +      typeof params === 'object' && !!Object.keys(params).length ? params : {};
Mismo **validateParams(data);**

2023-11-21 17:22 UTC, dam788 requested changes
corregite eso y lo paso

2023-11-21 17:22 UTC, dam788 commented on lib/utils/index.js
> +  typeof object === 'object' && !!Object.keys(object).length;
casi...quizás me exprese mal, la idea es que si pasa la validación devuelva params ó {}  que es la misma validación que utilizaste, pero la idea es que devuelta eso desde la util:

```
export const validObjectWithValues = (data) =>
  typeof data === 'object' && !!Object.keys(data).length 
     ? data
     : {}
```

2023-11-21 18:05 UTC, dam788 approved these changes

2023-12-12 20:04 UTC, christian97dd requested changes
tucu!, lo ví joya, te dejé unos comentarios de unos console logs que te quedaron nomas

2023-12-12 20:04 UTC, christian97dd commented on lib/analytics.js
> +    console.log('was called');
acá hay uno

2023-12-12 20:04 UTC, christian97dd commented on lib/analytics.js
> +      console.log('isDevEnv validation pass');
otro

2023-12-14 13:12 UTC, merged